-- Insert Categories
INSERT INTO categories (id, name) VALUES
('moteur', 'Moteur'),
('freinage', 'Freinage'),
('suspension', 'Suspension'),
('transmission', 'Transmission'),
('electricite', 'Électricité'),
('eclairage', 'Éclairage'),
('carrosserie', 'Carrosserie'),
('pneumatiques', 'Pneumatiques & Jantes');

-- Insert Subcategories
INSERT INTO category_subcategories (category_id, subcategory) VALUES
('moteur', 'Filtres à air'),
('moteur', 'Huiles moteur'),
('moteur', 'Bougies'),
('moteur', 'Courroies'),
('moteur', 'Joints'),
('moteur', 'Pistons'),
('freinage', 'Plaquettes de frein'),
('freinage', 'Disques de frein'),
('freinage', 'Liquide de frein'),
('freinage', 'Étriers'),
('freinage', 'Flexibles'),
('suspension', 'Amortisseurs'),
('suspension', 'Ressorts'),
('suspension', 'Silent-blocs'),
('suspension', 'Barres stabilisatrices'),
('suspension', 'Rotules'),
('transmission', 'Embrayage'),
('transmission', 'Boîte de vitesses'),
('transmission', 'Cardans'),
('transmission', 'Différentiel'),
('electricite', 'Batteries'),
('electricite', 'Alternateurs'),
('electricite', 'Démarreurs'),
('electricite', 'Bougies de préchauffage'),
('electricite', 'Fusibles'),
('eclairage', 'Phares'),
('eclairage', 'Feux arrière'),
('eclairage', 'Ampoules'),
('eclairage', 'Clignotants'),
('eclairage', 'Feux de brouillard'),
('carrosserie', 'Pare-chocs'),
('carrosserie', 'Rétroviseurs'),
('carrosserie', 'Vitres'),
('carrosserie', 'Portières'),
('carrosserie', 'Capots'),
('pneumatiques', 'Pneus'),
('pneumatiques', 'Jantes'),
('pneumatiques', 'Chambres à air'),
('pneumatiques', 'Valves');


